// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Repository;
using System;

namespace Repository.Migrations
{
    [DbContext(typeof(DecisoesContext))]
    [Migration("20171216215851_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Entities.Alternativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("ProjetoId");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Alternativa");
                });

            modelBuilder.Entity("Entities.Criterio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("ProjetoId");

                    b.Property<int?>("TipoDeDadosId");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.HasIndex("TipoDeDadosId");

                    b.ToTable("Criterio");
                });

            modelBuilder.Entity("Entities.MatrizDeDecisao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AlternativaId");

                    b.Property<int?>("CriterioId");

                    b.Property<int?>("ProjetoId");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("AlternativaId");

                    b.HasIndex("CriterioId");

                    b.HasIndex("ProjetoId");

                    b.ToTable("MatrizDeDecisao");
                });

            modelBuilder.Entity("Entities.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2017, 12, 16, 19, 58, 51, 324, DateTimeKind.Local));

                    b.Property<string>("Descricao")
                        .HasMaxLength(255);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Projeto");
                });

            modelBuilder.Entity("Entities.TipoDeDados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("TipoDeDados");
                });

            modelBuilder.Entity("Entities.Alternativa", b =>
                {
                    b.HasOne("Entities.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId");
                });

            modelBuilder.Entity("Entities.Criterio", b =>
                {
                    b.HasOne("Entities.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId");

                    b.HasOne("Entities.TipoDeDados", "TipoDeDados")
                        .WithMany()
                        .HasForeignKey("TipoDeDadosId");
                });

            modelBuilder.Entity("Entities.MatrizDeDecisao", b =>
                {
                    b.HasOne("Entities.Alternativa", "Alternativa")
                        .WithMany()
                        .HasForeignKey("AlternativaId");

                    b.HasOne("Entities.Criterio", "Criterio")
                        .WithMany()
                        .HasForeignKey("CriterioId");

                    b.HasOne("Entities.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId");
                });
#pragma warning restore 612, 618
        }
    }
}
